name: AuthMePremiumAutoLogin
main: me.kolorafa.bukkit.AuthMePremiumAutoLogin.AuthMePremiumAutoLogin
version: 0.1
description: Autologin and autoregister premium players at AuthMe
author: kolorafa
depend: [ PremiumProxy, AuthMe ]
